name:                sokoban
version:             0.1.0.0
github:              "sellleon/sokoban"
license:             BSD3
author:              "Leon Sell"
maintainer:          "sellleon@fim.uni-passau.de"
copyright:           "2019 LeonSell"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sellleon/sokoban#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - lens
  - containers
  - sdl2
  - sdl2-image
  - mtl
  - yaml
  - unordered-containers
  - text

executables:
  sokoban:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sokoban

tests:
  sokoban-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sokoban
